$root=(Get-Location).Path
$models=@('gemma-4-e2b','granite-4.2-3b','lfm2.5-2.6b','minicpm5-2b','ministral-3-3b','qwen3.5-4b')
$tasks=@('01-tris-web','02-tris-wpf','03-tesina-milano','04-tesina-obama','05-copy-milano','06-traduzione-marketing','07-multimodale','08-documenti','09-vendite')
foreach($m in $models){foreach($t in $tasks){New-Item -ItemType Directory -Force -Path (Join-Path (Join-Path $root $m) $t) | Out-Null}}
New-Item -ItemType Directory -Force -Path (Join-Path $root 'artefatti-comuni') | Out-Null
@'
Translate into Italian for a senior performance marketing team. Preserve technical meaning and use natural industry terminology, avoiding literal calques:
We are reallocating 20% of prospecting spend from broad paid social to high-intent search after the geo-lift test showed incremental ROAS below our contribution-margin break-even. Before scaling, deduplicate conversions across server-side events and the platform pixel, validate the attribution window, and segment cohorts by first-order CAC, LTV:CAC and payback period. Do not optimize for last-click ROAS alone: holdout markets suggest branded search is cannibalizing organic demand. Refresh the creative testing pipeline with three net-new hooks per audience, suppress recent purchasers, cap frequency, and monitor blended MER alongside marginal CPA. Report confidence intervals and seasonality-adjusted baselines, not just dashboard point estimates.
'@ | Set-Content -Encoding UTF8 (Join-Path $root 'artefatti-comuniprompt-traduzione.md')
@'
Analizza il file vendite.xlsx senza modificare i dati. Calcola: fatturato totale, unita totali, fatturato per canale, fatturato per categoria, prodotto con piu unita, AOV per ordine e percentuale fatturato da Ads. Indica metodo e eventuali limiti. Se non riesci a leggere xlsx, dillo esplicitamente: ti sara fornito il CSV identico.
'@ | Set-Content -Encoding UTF8 (Join-Path $root 'artefatti-comuniprompt-vendite.md')
$rows=@(@('id','data','canale','categoria','prodotto','unita','prezzo_unitario'),@('A01','2026-01-03','Ads','Casa','Lampada',2,30),@('A02','2026-01-04','Organico','Tech','Mouse',1,25),@('A03','2026-01-05','Ads','Tech','Mouse',3,25),@('A04','2026-01-06','Email','Casa','Tazza',4,10),@('A05','2026-01-07','Organico','Casa','Lampada',1,30),@('A06','2026-01-08','Ads','Casa','Tazza',5,10),@('A07','2026-01-09','Email','Tech','Mouse',2,25),@('A08','2026-01-10','Organico','Tech','Tastiera',1,80))
$csv=$rows | ForEach-Object {($_ | ForEach-Object {"$_"}) -join ','}; $csv | Set-Content -Encoding UTF8 (Join-Path $root 'artefatti-comuniendite.csv')
$dir=Join-Path $root 'artefatti-comuni'; Add-Type -AssemblyName System.IO.Compression
$fs=[IO.File]::Create((Join-Path $dir 'vendite.xlsx')); $zip=New-Object IO.Compression.ZipArchive($fs,[IO.Compression.ZipArchiveMode]::Create)
function add($p,$s){$e=$zip.CreateEntry($p);$w=New-Object IO.StreamWriter($e.Open());$w.Write($s);$w.Dispose()}
add '[Content_Types].xml' '<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>'
add '_rels/.rels' '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'
add 'xl/workbook.xml' '<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Vendite" sheetId="1" r:id="rId1"/></sheets></workbook>'
add 'xl/_rels/workbook.xml.rels' '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>'
$letters=@('A','B','C','D','E','F','G');$xml='<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>'
for($i=0;$i -lt $rows.Count;$i++){$n=$i+1;$xml+="<row r=""$n"">";for($j=0;$j -lt 7;$j++){$ref=$letters[$j]+$n;$v=$rows[$i][$j];if($i -gt 0 -and $j -ge 5){$xml+="<c r=""$ref""><v>$v</v></c>"}else{$xml+="<c r=""$ref"" t=""inlineStr""><is><t>$v</t></is></c>"}};$xml+='</row>'};$xml+='</sheetData></worksheet>';add 'xl/worksheets/sheet1.xml' $xml;$zip.Dispose();$fs.Dispose()
$colors=@{red=@(255,0,0);green=@(0,255,0);blue=@(0,0,255);yellow=@(255,255,0);magenta=@(255,0,255)}
Add-Type -AssemblyName System.Drawing
foreach($name in $colors.Keys){$c=$colors[$name];$bmp=New-Object Drawing.Bitmap(16,16);$g=[Drawing.Graphics]::FromImage($bmp);$g.Clear([Drawing.Color]::FromArgb($c[0],$c[1],$c[2]));$bmp.Save((Join-Path $dir ("colore-$name.png")),[Drawing.Imaging.ImageFormat]::Png);$g.Dispose();$bmp.Dispose()}
$rates=44100;$samples=88200;$freq=@(220,330,440,550,660);$w=New-Object IO.BinaryWriter([IO.File]::Create((Join-Path $dir 'toni.wav')));$w.Write([Text.Encoding]::ASCII.GetBytes('RIFF'));$w.Write([int](36+$samples*2));$w.Write([Text.Encoding]::ASCII.GetBytes('WAVEfmt '));$w.Write([int]16);$w.Write([short]1);$w.Write([short]1);$w.Write([int]$rates);$w.Write([int]($rates*2));$w.Write([short]2);$w.Write([short]16);$w.Write([Text.Encoding]::ASCII.GetBytes('data'));$w.Write([int]($samples*2));for($i=0;$i -lt $samples;$i++){$idx=[math]::Min(4,[math]::Floor($i/17640));$sample=[int16](9000*[math]::Sin(2*[math]::PI*$freq[$idx]*($i%17640)/$rates));$w.Write($sample)};$w.Dispose()
Write-Output 'Common assets and folders generated'
